order: 9
title: "PRODUCTIVITY"
description: "SELF-MANAGEMENT, HABITS, WORK OPTIMIZATION, ETC."
goals:
  - text: "Test"
    status: "u"
    deadline: ""
    dateCompleted: ""
    difftag: ""
    safetytag: ""
    tag1: ""
    tag2: ""
    tag3: ""
    tag4: ""
    tag5: ""
    info: ""
    refLink: ""
    resultLink: ""